### ISSUE TITLE
Converting from .groovy to .yml does not take into account environment blocks

### ISSUE THREAD

**Issue by sbglasius** [virtualdogbert/GroovyConfigWriter#1]
With this input 
```
dataSource {
    pooled = true
}
hibernate {
    cache.use_second_level_cache = true
    cache.use_query_cache = true
    cache.provider_class = 'net.sf.ehcache.hibernate.EhCacheProvider'
}
// environment specific settings
environments {
    development {
        dataSource {
            driverClassName = "com.mysql.jdbc.Driver"
            url = "jdbc:mysql://localhost/gr8cfp"
        }
    }
    test {
        dataSource {
            driverClassName = "org.h2.Driver"
            url = "jdbc:h2:mem:testDb"
        }
    }
    production {
        dataSource {
            driverClassName = "com.mysql.jdbc.Driver"
            url = "jdbc:mysql://localhost/gr8cfp"
        }
    }
}
```

I get:
```
dataSource: {pooled: true}
hibernate:
  cache: {use_second_level_cache: true, use_query_cache: true, provider_class: net.sf.ehcache.hibernate.EhCacheProvider}
```

I would have expected:
```
dataSource:
   pooled: true
hibernate:
   cache:
    use_second_level_cache: true
    use_query_cache: true
    provider_class: net.sf.ehcache.hibernate.EhCacheProvider
environments:
   development:
      dataSource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/gr8cfp
    test:
      dataSource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testDb
    production:
      dataSource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/gr8cfp
```
